  create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    discord_id bigint not null,
    name text null,
    constraint users_pkey primary key (id),
    constraint users_discord_id_unique unique (discord_id)
  ) tablespace pg_default;

 create index users_discord_id_idx
 on public.users (discord_id);

  create table
  public.games (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    constraint games_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.teams (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    intragame_team_id text not null,
    game_id bigint not null,
    constraint teams_games_fkey foreign key (game_id) references public.games (id),
    constraint teams_pkey primary key (id)
  ) tablespace pg_default;

 create index teams_intragame_team_id
 on public.teams (intragame_team_id);
 
  create table
  public.subscriptions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    team_id bigint not null,
    user_id bigint not null,
    constraint sub_team_fkey foreign key (team_id) references public.teams (id),
    constraint sub_user_fkey foreign key (user_id) references public.users (id),
    constraint subs_pkey primary key (id)
  ) tablespace pg_default;