  create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    discord_id text not null,
    constraint users_pkey primary key (id),
    constraint users_discord_id_unique unique (discord_id)
  ) tablespace pg_default;

 create index users_discord_id_idx
 on public.users (discord_id);

  create table
  public.games (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    constraint games_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.teams (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    game_id bigint not null,
    constraint teams_games_fkey foreign key (game_id) references public.games (id),
    constraint teams_pkey primary key (id)
  ) tablespace pg_default;



-- create table
--   public.players (
--     id bigint generated by default as identity,
--     created_at timestamp with time zone not null default now(),
--     name text not null,
--     team bigint null,
--     position bigint null,
--     dob date not null,
--     sleeper_search_rank bigint null,
--     sleeper_id bigint null,
--     constraint players_pkey primary key (id),
--     constraint players_team_fkey foreign key (team) references teams (id),
--     constraint players_position_fkey foreign key ("position") references positions (id)
--   ) tablespace pg_default;

--   create table
--   public.users (
--         id bigint generated by default as identity,
--         created_at timestamp with time zone not null default now(),
--         discordId bigint not null,
--         constraint users_did primary key (discordId)
--   ) tablespace pg_default;

--  create table
--   public.games (
--      id bigint generated by default as identity,
--      created_at timestamp with time zone not null default now(),
--      text not null
--    ) tablespace pg_default;

-- --    create table
-- --   public.teams (
-- --      id bigint generated by default as identity,
-- --      created_at timestamp with time zone not null default now(),
-- --      name text not null,
-- --      gameId,
-- --      constraint team_gameId_fkey foreign key ("gameId") references games (id)
-- --    ) tablespace pg_default;
